name: medusa_js_dart
publish_to: none
resolution: workspace
description: A Dart client for interacting with the MedusaJS API.
version: 0.0.6
homepage: https://github.com/agostinofiscale/medusa-js-dart

environment:
  sdk: '^3.9.2'

dependencies:
  copy_with_extension: ^10.0.1
  dio: ^5.9.0
  dio_smart_retry: ^7.0.1
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.6.0

dev_dependencies:
  build_runner: ^2.10.1
  copy_with_extension_gen: ^10.0.1
  json_serializable: ^6.11.1
  lint: ^2.8.0
  retrofit_generator: ^10.1.1
  test: ^1.26.3
